### PR TITLE
Shorthand numbers for ScreenDialogAmount control

### PR DESCRIPTION
**Pull request by UberMouse**
Expands shorthand numbers to full numbers. I've gotten used to this from Runescape and it's convenient for moving items around. Works with both period and comma decimal separators and is case insensitive.  
2k == 2000
2.62k = 2620
1m = 1,000,000
1b = 1,000,000,000

### CODE REVIEW

**Comment by MMaster** [comment]
Why is this needed in game code? Also Regex is terribly slow.

**Comment by UberMouse** [comment]
I'm not really sure what type of PRs are being looked for, I just made this for myself because I wanted the feature and figured I'd see if it would be of any interest, happy to close if not. 

I took the slowness into consideration, but that function is only called when the up/down/confirm buttons are pressed so it's not called frequently. I just tested, to construct and match 100 regexps it takes 1ms.

**Comment by zrisher** [comment]
Yeah 100 in 1ms is pretty slow, but if it's only called on `TryParseAndStoreAmount()` it should be fine right?

I suggest squashing your commits together.

**Comment by UberMouse** [comment]
It could at most be called once per frame if the the up/down buttons were being mashed. 

Just squashed them.

**Pull request closed without merging**
