### PR TITLE
Toolbar/Button config window fix and performance improvements

### PR DESCRIPTION
**Pull request by andrew-w**
Improved toolbar config window (G key) grid population speed. Previously with 300+ mods in my world, it would take 5 minutes to populate the grid if I selected "Large Blocks" as the filter.  Now, it takes just a second or so to populate.

Improved toolbar config window grid sizing.  The window now calculates the rows needed and no longer scrolls if there are less rows than the screen height.
Bug-Fix:  In the opposite respect, the grid now shows all the rows needed for a selected category.  Previously, if selected category required more than 63 rows to display all the available blocks, you would not see them all, it would only show 63 rows.

Button config window (K key) speed improvement.  As per the toolbar grid config window, this  configuration window has had its performance improved.  Again, with lots of blocks on the grid, opening the button panel configuration window could take a few minutes to populate the available
blocks.  Now it shows in just a second or two.

### CODE REVIEW

**Comment by mexmer** [comment]
can you give some measurements with real values?
also imo better solution will be, if list is not recreated with each opening, but list is destroyed upon world load, and created on first access, and then remain static.
it's not that modules add new blocks over time, they remain same, so if you clear list of blocks on G-Menu at start of game (or end of game), it would be even more efficient.

**Comment by andrew-w** [comment]
I'll certainly do some real measurements later on when I get home from work, but what I can say in the mean-time is that with 320 mods loaded in my world.  With the toolbar config window already opened, clicking on the "Large Blocks" category originally took 4 minutes and 40 seconds to filter and display the blocks.  Now, it takes just 2 seconds.
What was happening, "ItemIds" in "MyCategoryClassDefinition.cs" was filled with many duplicate id's from the mod loading process.  There was about 519 thousand id's in that list that had to be iterated to see if they matched the chosen id.  Therefore, I changed the list to a hashset so that duplicate entries are just discarded which drastically reduced the number of entries, hence drastically reducing the filtering times.

I agree with your suggestion about only creating the list at start or end of game, since as you say, blocks are never added or removed during a session.  That would be a much bigger change and it'd be great to get the speed improvements that I've already duke into the game quickly, since playing my world is a nightmare when configuring toolbars and buttons.
So, if I were to look at doing that, I'll probably make another branch for it.

Thanks for your feedback though :)

**Comment by mexmer** [comment]
that sounds promissing.
how this solves issue, when 2 mods have block with same name?

**Comment by andrew-w** [comment]
Unfortunately, I can't get values for the version that I've submitted, as for some weird reason, tonight every time I try to load my scene with the mods, I get an out of memory error in a Draw call for a dds texture and that terminates the game.  Therefore I cannot get to the toolbar config screen to get the new faster times.

Hopefully keen either will not have the issue, or will know how to deal with it if it crops up.  They will however, have to choose 320+ mods to load in to compare old against new.  I can supply the list of mods I'm using if keen needs it.

Anyway, I did manage to get the slower times from the original version of course and they are as follows:

I used the space base starter map as my map, but added the 320 odd mods that I use on my DS.  The load time  to get into the game is 5m 40s.  This is still the same in my modified code, since I have not touched the loading routines.

Once in the game, opening the toolbar config window the first time takes 5 seconds.  (The "All blocks" category is selected by default doesn't seem to have the slow-down).
Selecting "Weapons and Tools" category takes 37s to populate.
Selecting "Large Blocks" category takes 4m 48s to populate.

Last night when things were working, my modified code only took 2-3 seconds to populate the "Large Blocks" category, a massive performance increase.

Opening a "Button Config" screen by pressing "K" on a button block, tool 22s to populate in the original code, but I was able to get to this window in my modified version and it was instant!

Looking at the code, the culprit seems to be the "ItemIds" list which I changed from a List<string> to a Hashset<string> to prevent duplicates.  With the unmodified code, there seems to be 148 categories each with a list of "ItemIds" and it is these categories and ID lists which are iterated which cause the slowdown.
I did not inspect all 148 of the categories, three that I did look at, each had an "ItemIds" list with a count of 509,816 entries, 312,000 entries and 50,200 entries.  So, if you consider that there are 148 categories that will be iterated, and just three of them have that number of "ItemIds" to iterate, then there is a very large number of item id's to iterate and thus the very slow toolbar and button config windows.

In answer to your question about when 2 blocks have the same name, as far as I can see, this would not be an issue.  The section of code that iterates the "ItemIds" list, returns true if the item ID was found and false if not. Therefore, removing the duplicate entries should have no adverse effect.  In fact, I'd be more worried about 2 different blocks having the same ID.

Anyway, it's all down to keen approving the changes, and I sure hope they do soon!!!!  As it'll make my DS a lot more pleasing to play, since I waste so much time waiting for the toolbar and button config windows to populate.  Plus, as an added bonus, I'll be able to see all the block I've added since I fixed the toolbar config window not showing all the blocks.

Hope that gives you some useful info.

**Comment by mexmer** [comment]
out of memory issues might occur, since you debuging 32bit version, i would suggest switching to 64bit for debugging purpose (i posted link to howto on forums).

or maybe, if load just empty world (and i mean Empty world, really), since you only need to test K/G menu fuctionality. that might help

**Comment by andrew-w** [comment]
I did suspect the 64bit thing, but I'll give the empty world a try first as that's a lot easier from the sounds of it.

In terms of testing the functionality, I did that before I submitted the pull request, so I'm happy with the way those screens work, and their speed.  It's just that I didn't note down the faster times which is what I'm having trouble trying to get with the memory issues.

I'll give the empty world a go now, if that doesn't work I'll try the 64bit workaround another day..  it's getting pretty late here.

**Comment by andrew-w** [comment]
Ok, I have some comparison numbers.

In the (G) config window.
Selecting "Weapons and Tools" category:
Pre Fix - 37 seconds to display items
Pre Fix - MyCategoryClassDefinition::ItemIds count: 50,204
Post Fix - Instantly populates items.
Post Fix - MyCategoryClassDefinition::ItemIds count: 57

Selecting "Large Blocks" category:
Pre Fix - 4 minutes and 48 seconds to display items.
Pre Fix- MyCategoryClassDefinition::ItemIds count: 509,816
Post Fix - 0.7 seconds to display items.
Post Fix - MyCategoryClassDefinition::ItemIds count: 781

Again, I hope keen get's this fix merged in soon, as playing on my DS is painfully slow without this fix.

**Comment by FavioGalvis** [comment]
I support and agree with this PR, even with a low count of mods (34 in my case) there is a 5 to 7 seconds delay in the G menu.
This prety much solve this.
Great work @andrew-w !

**Comment by andrew-w** [comment]
Thanks Favio!  Glad somebody else will feel a benefit from this!

I know I will, as it'll make a massive difference to the playability on my server, so I keep checking here every day in the hope that keen merges this in!    Soon, hopefully..  fingers crossed....

**Comment by FavioGalvis** [comment]
:+1:

**Comment by FavioGalvis** [comment]
BUMB! for relevance. This is perfect for the end user!

**Comment by FavioGalvis** [comment]
Why is this not getting merged? What is going on Keen? You are not debugging, and you are also not supporting modder debbug?

**Comment by devu** [comment]
Good question. I am running a DS and creating custom mod for it. 7 types of
armor with full range of blocks (20+ each type) and already noticed
performance drop.
My goal is to create MMO style like game on top of SE. But those kind of
things only shows me how naive I am.

This improvement is one of the MUST HAVE if we heading towards sandbox
style game.

**Comment by andrew-w** [comment]
Yup, I'm still waiting anxiously for this to go into the game.  The bigger my space station gets the longer wait times I have for setting up buttons etc.

I'm now at 1min 40secs just to open the (K) config window, so as you can imagine, I've stopped setting up timers, button, cockpits etc because I waste a massive amount of time staring at a locked screen.  Which is a huge detriment to the gameplay as it's a core part of it.  Which brings me to note that I never previously mentioned that setting up timer blocks is also affected by this slowness too.

Please keen!  get back to implementing at some of the community fixes/improvements, we need this one at least!!!  ;)

**Comment by kurevin** [comment]
Friendly bump. As a person who uses ~200 mods I have to say that this is a MUST.

**Comment by devu** [comment]
Well, I am using just few, but one provides 7 types of armor with greater
choice of blocks (40 each) and... same story.
It is a must! Not to mention memory leak associated with it.

**Comment by zrisher** [comment]
:+1:, but @kurevin take a look around and you'll see KSH stopped accepting PRs many weeks ago. The notes on a patch a couple weeks ago mentioned that github issues and PRs were last priority for them right now, which means they're not getting reviewed at all until planets are released (would be my guess).

**Comment by devu** [comment]
We need KSH recognize that DS is a driving force of this community, not any
of features/bug fixing they planing to add or improve including planets
will change the fact, that players leaving this game unless they cannot
play, enjoy the game with their fellas. And in order to provide the game
play we need to rely on mods. It was KHS intention from the start to make
it modifiable and true sandbox type game. If they will fail on this,
planets will not help. If game performs badly with them this is even bigger
push for more players out of multiplayer community. Single Players will
enjoy it only for few weeks before get bored. I know there is a common say,
early optymalization is a root of all evil, but lack of it is a dead end.
This game is falling apart because of it. We need to press more on things
are crucial or simply say goodbye to ambitious group that failed to
deliver. I am running server that is high in official ranking and I can
tell the trend. Wonder how long I can hover my cursor over shout down
button.

**Comment by Atulin** [comment]
Oh yes... That's what I was waiting for.

I may not have 300+ mods, but I do have a considerable amount, and waiting for the G menu to pop up each time is... Well, not fun. Quite the opposite.

Too bad Keen apparently forgot about this Github and does nothing about those community fixes.

**Comment by MasterSurge** [comment]
Just asking, how would I be able to implement this myself into Space Engineers?

**Comment by vtecem** [comment]
Agreed, this needs implementing!

**Comment by FavioGalvis** [comment]
bump for relevance.

**Comment by IhanaMies** [comment]
This is brilliant!

**Comment by andrew-w** [comment]
Thanks for merging this in!

Unfortunately, it seems there is an issue or two with the fix; some items not showing up in the G-Screen.  not sure if that's due to changes since I did this (new block types etc), or whether I just didn't see them before with the blocks that weren't new.
Either way, I'm trying to look at fixing the problems, but after updating to the latest merge of the project, it seems that the codebase is very broken and I cannot compile the project.  This has been reported by other people and there is even an "issue" ticket for it.

Any chance of getting the repo fixed up?
Then I can look at the fixes, otherwise it's going to fall back to Keen to do it, which I'm sure they probably wont be too happy about :(

**Pull request merged**
