### PR TITLE
Allow modding the Laser Antenna's line-of-sight requirements

### PR DESCRIPTION
**Pull request by Phoenix84**
Added the option for modders to create laser antennas unrestricted by the line-of-sight requirement.

### CODE REVIEW

**Comment by mexmer** [comment]
you know it's laser ... it cannot pass trough material, therefore it requires LoS

this is question of principle. wait for regular directional antena

**Comment by Phoenix84** [comment]
In the code, what's the difference between laser and regular directional antenna?
With this, you now have a directional antenna.

I understand what you mean by 'laser', but I didn't change the default behavior, I exposed functionality for it.
I was also not aware it was 'in-progress,' as there's no reference to it in code.

**Comment by mexmer** [comment]
you have good point here. most likely from code point of view, there will be no difference, since p2p antena connection doesn't require to eval list of broadcaster, it just need to track endpoint.

and idk if they are in progress (directional antenas), it just would make sense to me, if they are.

also don't forget to add value to cubeblock.sbc

**Comment by Phoenix84** [comment]
I thought about cubeblocks, but I wasn't sure if that was necessary.
The only reason to change it would be for an example, as it has a default value already.
Is that a general rule to follow then?

**Comment by mexmer** [comment]
i think so ... when you add parameter to definition for block builder, you need also add it to block definition data.

**Comment by OndrejPetrzilka** [comment]
We will probably rename laser antenna to p2p antenna later.

**Pull request merged**
