### PR TITLE
Extracted magic constant.

### PR DESCRIPTION
**Pull request by mafagafogigante**

### CODE REVIEW

**Comment by YotaXP** [comment]
I know that UNDERSCORE_CASE has been used elsewhere in the code, but should we encourage its use?  It's against .Net naming conventions, and inconsistent with constants like `CornerCount`.

**Comment by mafagafogigante** [comment]
Good catch. I am so used to uc that it just happened. I can change it, though.

**Comment by mafagafogigante** [comment]
Done.

**Comment by Spartan322** [comment]
I guess KSWH so rushed themselves they forgot about using constants?

**Comment by mafagafogigante** [comment]
I am not a guru myself, but unless you overtime under a load of coffee, you should spot a literal repeated 6 times easily. Not only a literal, but a very f-up constant that almost asks for its own field.

**Comment by Spartan322** [comment]
Yup

**Comment by No-Brain** [comment]
Doesn't do anything. Don't be that guy.

**Comment by JCMais** [comment]
Wait, what? So we should be the guy that keep magic numbers around?

So what type of of PR are you guys accepting? No code cleanups? Only new features? Is that it?

**Comment by g4borg** [comment]
I guess he meant, don't be that guy who mocks others' code as if he would have never overlooked stuff or even written bad code; It is easy to spot errors in others' code. We all do it constantly.

**Comment by mafagafogigante** [comment]
This is more than ridiculous. You go "open source" with a game whose development is far from finished and do not accept a magic constant extraction because it *doesn't do anything*.

@JCMais Also didn't get it.

@g4borg I don't think that he meant that. Just ignored valid refactoring.

**Comment by MMaster** [comment]
I think I understand it. Changing code just to make it 'nicer' is not a valid reason to make pull request. If you will have some feature or fix that will be related to this then it makes sense to squeeze it in, otherwise it is not necessary to change code that works correctly.

**Comment by mafagafogigante** [comment]
You may understand their reasons to close the PR. But guess what, I also so. The point is that a refactoring like this would made it to Guava or the Linux kernel (magic constants don't exist in those places btw). It is absurd not to merge something just because everything must be a feature or fix.

**Comment by MMaster** [comment]
I understand your point and I understand their point. This is not open-source project - it is product owned by company that needs to test it and make sure that everything works because they sell it. Even if it is early access the approach is a bit different than in open-source. Please don't get mad because of it. It's not a big deal - they decide what goes in and what not as it is their code. We can just propose changes. Just accept it and move on :)

**Comment by mafagafogigante** [comment]
I'm accepting their decision (not doing so is not an option, anyways). I'm just dazzled by how stupid it is. @JCMais also got this.

A close without merge would be OK if the reason is what @YotaXP pointed out, but I even got to fix it.

**Comment by zrisher** [comment]
I also think it's a little surprising this was closed. What's the harm in letting people submit PRs for small code quality fixes? Even if it's not a major change, it takes two seconds to accept.

**Comment by mafagafogigante** [comment]
Even if you only merge locally, it takes really little time to merge.

**Comment by Spartan322** [comment]
It was probably closed because it creates a useless commit, which should come along another commit, often time people don't accept (Github) PRs because the commits are either useless or poorly described, if this wants to get merged, it needs to be of much higher importance.

**Comment by zrisher** [comment]
But it's not "useless" because it has some value, even if that value is small. And what's the downside of having more commits in the history? I agree that if many commits are added at once that are related, they should be squashed. But otherwise there seems to be no disadvantage to having one more commit in there.

**Comment by mafagafogigante** [comment]
Makes no sense. Serious projects such as rails understand the value of these commits. Additionally, each commit should be atomic, presenting only one change to the repo.

**Comment by Spartan322** [comment]
There is actually no help that this PR would provide if accepted, please stop complaining about it now.

**Pull request closed without merging**
