### PR TITLE
Input Interface

### PR DESCRIPTION
**Pull request by THDigi**
Input interface (IMyUserInput) for reading keyboard, mouse and joystick.

Accessible via MyAPIGateway.Session.Input for modders.

### CODE REVIEW

**Comment by stafyniaksacha** [comment]
Will it be accessible for in-game scripting ?

**Comment by THDigi** [comment]
This is the overall input for the current player, so scripts won't (and shouldn't) access this.

For in-game scripts it would require synchronizing to update the IMyShipController with the input that the pilot/RCer is sending, but first things first :P

Having this first layer of input would also allow modders to make something that in-game scripts can use, for example if you're in a cockpit it will send the actions as arguments to a specific PB which can do whatever with the information, until a proper synchronized interface is made specially for in-game scripts.

**Comment by THDigi** [comment]
Fixed merge conflicts with this as well (also sneakily xD)

**Comment by THDigi** [comment]
Merge conflicts solved again :}

**Comment by THDigi** [comment]
Fixed merge issues :}

**Comment by OndrejPetrzilka** [comment]
I will merge this, but it may not be compatible with our future input changes. We would like to rewrite it.

**Comment by mexmer** [comment]
unfotrtunately, this PR was not cleaned properly, missing namespace changes for MyStringId as well as adding file in project, that no longer exists.

```
diff --git a/Sources/Sandbox.Common/ModAPI/IMyControl.cs b/Sources/Sandbox.Common/ModAPI/IMyControl.cs
index ee0a940..95c44d3 100644
--- a/Sources/Sandbox.Common/ModAPI/IMyControl.cs
+++ b/Sources/Sandbox.Common/ModAPI/IMyControl.cs
@@ -5,6 +5,7 @@

 using VRage.Input;
 using VRage.Library.Utils;
+using VRage.Utils;

 namespace Sandbox.ModAPI
 {
diff --git a/Sources/Sandbox.Common/ModAPI/IMyUserInput.cs b/Sources/Sandbox.Common/ModAPI/IMyUserInput.cs
index 494697c..6c1c19e 100644
--- a/Sources/Sandbox.Common/ModAPI/IMyUserInput.cs
+++ b/Sources/Sandbox.Common/ModAPI/IMyUserInput.cs
@@ -6,6 +6,7 @@
 using VRage.Input;
 using VRageMath;
 using VRage.Library.Utils;
+using VRage.Utils;

 namespace Sandbox.ModAPI
 {
diff --git a/Sources/Sandbox.Common/MyControlWrapper.cs b/Sources/Sandbox.Common/MyControlWrapper.cs
index d99878f..77ddd3a 100644
--- a/Sources/Sandbox.Common/MyControlWrapper.cs
+++ b/Sources/Sandbox.Common/MyControlWrapper.cs
@@ -5,6 +5,7 @@

 using VRage.Input;
 using VRage.Library.Utils;
+using VRage.Utils;

 namespace Sandbox.ModAPI
 {
diff --git a/Sources/Sandbox.Common/Sandbox.Common.csproj b/Sources/Sandbox.Common/Sandbox.Common.csproj
index 7011ce1..d245586 100644
--- a/Sources/Sandbox.Common/Sandbox.Common.csproj
+++ b/Sources/Sandbox.Common/Sandbox.Common.csproj
@@ -278,7 +278,6 @@
     <Compile Include="Models\MyIntersectionResultLineTriangle.cs" />
     <Compile Include="Models\MyMesh.cs" />
     <Compile Include="Models\MyMeshMaterial.cs" />
-    <Compile Include="MyAbstractXmlSerializer.cs" />
     <Compile Include="MyControlWrapper.cs" />
     <Compile Include="MyDefinitionErrors.cs" />
     <Compile Include="MyEngineConstants.cs" />
diff --git a/Sources/VRage.Input/MyUserInput_ModAPI.cs b/Sources/VRage.Input/MyUserInput_ModAPI.cs
index 862d4c1..303bea4 100644
--- a/Sources/VRage.Input/MyUserInput_ModAPI.cs
+++ b/Sources/VRage.Input/MyUserInput_ModAPI.cs
@@ -6,6 +6,7 @@
 using Sandbox.ModAPI;
 using VRageMath;
 using VRage.Library.Utils;
+using VRage.Utils;

 namespace VRage.Input
 {
```

**Comment by No-Brain** [comment]
We had to revert this internally because this introduces circular dependency on sandbox.common.

**Comment by THDigi** [comment]
@No-Brain 
Would this be better ? https://github.com/THDigi/SpaceEngineers/commit/01cb0daf20b0e0a2ab79e944e3e69409e2f14749

Moved the interfaces to VRage.Game/ModAPI but VRage.Input requires to reference VRage.Game for that to work.

**Pull request merged**
