### PR TITLE
Allow editable mission screen in ModAPI

### PR DESCRIPTION
**Pull request by Spcemarine**
- added the argument editEnabled to the API methods
- added a parameter that contains the text of the mission screen to the
  callback

Note: This might be a breaking change for some scripts because it modifies the callback Action but I'd find it quite useful.

### CODE REVIEW

**Comment by Tyrsis** [comment]
Needs to be backwards compatible.  A lot of mods use this screen as a way to display information.  Just make an editable mission screen something completely or maybe try to figure out a way of overloading the current method.

**Comment by Spcemarine** [comment]
As long as you haven't specified a callback action (what is supposed to be the case when you just display information) it is compatible.
The current solution is the easiest and the most logical for the API (at least in my opinion). Creating a second method would be weird because it would be some kind of duplication. Furthermore a lot of mods use methods or interfaces that change sometimes. Our mod breaks approximately every two versions, so I'm not really motivated to change that as long as someone from KSWH asks me to do it.

**Comment by Tyrsis** [comment]
So you expect everyone to fix their mod because you would find the feature useful?  That isn't playing nice.  But you're right, let KSWH decide.  Though look at other pull requests that do not provide backwards compatibility, and you'll notice a trend that they tend not to merge those.

**Comment by Spcemarine** [comment]
Well, 'everyone' is a little hard, don't you think so? It's only the case if someone really uses the callback, all other mods won't be affected. However, I wouldn't mind if there never are breaking changes but I don't get double standards.

**Comment by MeusRex** [comment]
From what I could glean from the Asteroid generator PR, PR's are required to be backwards compatible. https://github.com/KeenSoftwareHouse/SpaceEngineers/pull/58

**Comment by Spcemarine** [comment]
But that is about the main game, not modding stuff, isn't it?

**Comment by MeusRex** [comment]
Hmm, no idea. I guess we'll have to wait for a dev to comment.

**Comment by Spcemarine** [comment]
Yes. That makes me wondering if the devs are going to release some sort of guidelines. Would be good to know what we are allowed to do and what we shouldn't.

**Comment by MeusRex** [comment]
Idd. Would be quite useful.

**Comment by No-Brain** [comment]
Everything should be backwards compatible. Especially when there is no problem to do it without hacks like in this case.

**Comment by Spcemarine** [comment]
Ok, then I'll just make sth like ShowEditableMissionScreen(...).

**Pull request closed without merging**
