### PR TITLE
Added 2 decimal places to Oxygen Tank capacity 

### PR DESCRIPTION
**Pull request by Geneticus**
Due to Oxygen Farm production being as slow as it is. The time for 1 Farm to add 0.01% to a tank made it difficult to tell if things were working and connected correctly.

### CODE REVIEW

**Comment by Geneticus** [comment]
I see that. 1st commit via Git, lessons learned :)

**Comment by mexmer** [comment]
@Geneticus user.props is in .gitignore so, you can modify it outside project as much, as you want, and will never be pushed, but when you touch it with visual studio. that's different matter. it become part of solution.

i had this few times with other SCM, well except TFS ... but TFS is microsoft thing.

**Comment by Geneticus** [comment]
So the question is should I leave it as is? Close it, revert,  and reissue the pull or other?

**Comment by mexmer** [comment]
just revert change in solution file, that's all.

**Comment by thelastWallE** [comment]
Or you can exclude user.probs in the Team Explorer if you edited or created the file in Visual Studio.

**Pull request merged**
