### PR TITLE
Expose Power getters of Reactor, Solar and Battery for ingame scripts

### PR DESCRIPTION
**Pull request by MMaster**
Expose CurrentPowerOutput and MaxPowerOutput of Reactor, Solar Panel and Battery for ingame scripts. Also exposes CurrentPowerStored and MaxPowerStored for Battery.

### CODE REVIEW

**Comment by bfosberry** [comment]
:+1:

**Comment by pipakin** [comment]
Yes please!

**Comment by mattgiltaji** [comment]
This would be really useful for me

**Comment by Spartan322** [comment]
:+1:

**Comment by Geneticus** [comment]
Does this add the stats to the block info panel in the control panel as well?

**Comment by NivvyDaSkrl** [comment]
I endose this product and/or service.

**Comment by MMaster** [comment]
@Geneticus afaik all of those are already shown in details text.

**Comment by mexmer** [comment]
@MMaster parsing info from detailed info is quite inconvenient. Also there is lot more to PowerProducer, you might want to know.

**Comment by MMaster** [comment]
@mexmer Geneticus was asking if this does add stats to detail text. I just replied to him that that is already there. I know that parsing it from detailed info is inconvenient I did do Automatic LCDs :) Thats why I issued this pull request.

**Comment by mexmer** [comment]
@MMaster my bad, didn't look at context of discussion properly

**Comment by OndrejPetrzilka** [comment]
I've merged it and then created interface Sandbox.ModAPI.Ingame.IMyPowerProducer so scripts does not need to differentiate between different power producers to make same thing.

**Comment by MMaster** [comment]
Awesome! That's much better. Thank you.

**Comment by FKuerten** [comment]
Does anyone know why this was reverted in 1c4032eebb9c277ed759e8d2c34d90c291d918e7?

**Comment by mexmer** [comment]
@FKuerten resource management has been reworked, therefore this is no longer valid. atm. there is no access to power system

**Pull request closed without merging**
