### PR TITLE
Increase number of toolbars to 9

### PR DESCRIPTION
**Pull request by aaraujo666**
Increases the number of toolbars to 9 since this seems to be a popular request among players

### CODE REVIEW

**Comment by Spartan322** [comment]
Wouldn't it make more sense for PageCount and SlotCount to use the DEF_PAGE_COUNT and DEF_SLOT_COUNT constants respectively.

**Comment by aaraujo666** [comment]
I agree, but I just changed the value, the code was already like that.

**Comment by Spartan322** [comment]
Magic Numbers are really annoying but ok, also, why are PageCount and SlotCount being set before construction and then being set again in the constructor, when you can't construct MyToolbar any other way, that also makes no sense.

**Comment by Eikester** [comment]
i'd like a dynamic setup i.e. only add new toolbars if the old one is full

**Comment by zrisher** [comment]
Awesome!!

**Pull request merged**
