### PR TITLE
Drill push items if volume >= slider value(0-100%)

### PR DESCRIPTION
**Pull request by KionX**
allows you to use the drill as a container for the storage of ore
eliminates spam ore(useful for autosorting mods)
optimization

### CODE REVIEW

**Comment by JJRcop** [comment]
You should instead force pull from upstream to your master, make the branch again, and start over. To avoid the junk commits that add something then revert it.

**Comment by mexmer** [comment]
also use rebase instead of merge when pulling from remote upstream (keen source)

**Comment by No-Brain** [comment]
No description provided.
Why do we need this?

**Comment by KionX** [comment]
allows you to use the drill as a container for the storage of ore
eliminates spam ore(useful for autosort mods)

**Comment by No-Brain** [comment]
Drills are already used as storage when there is no place to put the ore.
This is not an optimization in any way shape or form as this has even worse performance from additional game logic and extra bandwidth requirements.

**Comment by KionX** [comment]
I watched the code. and I see that every time there is sending packets with information about the shifting of ore

sometimes it is necessary that the ore remained in the drill. so as not to interfere other items

**Comment by No-Brain** [comment]
The only thing this does is delay the moving by 100 frames. It is exactly the same from that point.
This also wastes resources when the drill is full.

**Comment by KionX** [comment]
this idea comes from my personal experience.
I find it useful. and the game loses nothing from this option.

**Comment by No-Brain** [comment]
This doesn't improve anything. Adds no depth to the gameplay, just more complexity and ways to let the user shoot themselves in the foot.

**Comment by KionX** [comment]
and I think that the upgrade modules for the refinery does not add depth.
you are too categorical.

**Comment by KionX** [comment]
if you keep the ore in a drill you can save on containers into survival

**Comment by mexmer** [comment]
if you don't have container, ore is not pushed out, but stored in drill even now.

when i use my drill drone, i always fill cargo, connector and drill to full, until i head back, if i remove cargo, i can build "smaller" drone, but i don't see benefit in that.

**Comment by KionX** [comment]
I do not mean it. ore store in drill and the rest in other containers.
this is useful when resources are limited or when digging is not important.

**Comment by JJRcop** [comment]
@KionX Your master is tainted, so any branch you make is not based off of master and includes junk commits. You should fix that by inputting these git commands on your local repo
```
git checkout master
git fetch https://github.com/KeenSoftwareHouse/SpaceEngineers.git master
git reset --hard FETCH_HEAD
git push --force origin master
```

**WARNING: THIS WILL DELETE ALL OF YOUR UNMERGED COMMITS ON THE MASTER BRANCH**

Copy-pastable version:
```git checkout master;git fetch https://github.com/KeenSoftwareHouse/SpaceEngineers.git master;git reset --hard FETCH_HEAD;git push --force origin master```

After this, just make new branches when you want to develop another feature, and do not commit to master.

**Pull request closed without merging**
