### PR TITLE
Extending interfaces for Role Play mod.

### PR DESCRIPTION
**Pull request by JimLess**
+ ChangeModelAndColor(model, colorMaskHSV); - for changing spaceman
model by client side script.

### CODE REVIEW

**Comment by JimLess** [comment]
I plan to expand the interface. Any objections?
situation: the player buys different types suit for game currency. (implemented)

**Comment by mexmer** [comment]
when adding interfaces or fields or methods to interface, add also ///<summary> , so it will be reflected in documentation.

and yes, i'm aware that many existing interfaces doesn't have it, but it's common sense to add it anyway.

///<summary> is processed by sandcastle, which is used to create api documentation file

https://msdn.microsoft.com/en-us/library/2d6dt3kf.aspx

**Comment by JimLess** [comment]
Ok. I do this soon.

**Comment by mexmer** [comment]
thanks

**Comment by JimLess** [comment]
Please check this out.

**Pull request closed without merging**
