### PR TITLE
Ammo consumption fix for MySmallGatlingGun

### PR DESCRIPTION
**Pull request by joemorin73**
Fix for https://github.com/KeenSoftwareHouse/SpaceEngineers/issues/213

This corrects the ammo consumption in multiplayer environment by adding IsServer check.

### CODE REVIEW

**Comment by zrisher** [comment]
Huge, huge issue in Multiplayer. I would really like to see this incorporated.

**Comment by Tyrsis** [comment]
I've added about 3 reports and even videos showing this problem in closed testing.  And completely forgot about it once source was released, so great that you found it.  It's very obvious that ammo is just being double dipped now that I look at it.  Simple fix for a very annoying problem.

**Comment by joemorin73** [comment]
It's one of those things that's obvious once you see it.  I only figured it out once I saw a correlation between ammo consumption and users.

**Comment by zrisher** [comment]
Perhaps instead of adding this check to `MySmallGatlingGun.Shoot()` and `MyLargeTurretBase.RemoveAmmoPerShot()`, you should add it to `Sandbox.Game.Weapons.MyGunBase.ConsumeAmmo()` instead, which both functions call to consume the ammo.

image

That would allow you to:
* Also fix this bug for handheld weapons
* Unify how this check is done by removing the duplicate `Sync.IsServer` check in `MySmallMissileLauncher.Shoot`
* Ensure this fix is not dropped later when more weapons base types are added

**Comment by joemorin73** [comment]
@#$%, you're right.  I was too busy focusing on the replicating MySmallMissileLauncher's code that was working that I didn't think further.  I'll be putting in a new pull request.

**Comment by joemorin73** [comment]
Closing in favour of other PR

**Pull request closed without merging**
