### PR TITLE
Added IMyOxygenBottle with OxygenLevel property

### PR DESCRIPTION
**Pull request by Sibz**
Enables retrieval level of oxygen in the bottle as float 0-1.
I.e. 0.5 = 50%
Usage Example:
```c#
var OxyGen = GridTerminalSystem.GetBlockWithName("Oxygen Generator");
var inv = OxyGen.GetInventory(0);
var items = inv.GetItems();
items.ForEach(item =>
{
  if (item.Content is IMyOxygenBottle)
    Echo("OxyLevel:" + (item.Content as IMyOxygenBottle).OxygenLevel);
});
```
Compiled and Tested OK.

### CODE REVIEW

**Comment by Sibz** [comment]
@mexmer It is:
Sources/Sandbox.Game/MySandboxGame.cs
```c# IlChecker.AllowedOperands.Add(typeof(Sandbox.ModAPI.Interfaces.IMyOxygenBottle), null);```

**Comment by lord-devious** [comment]
If it is intended for use in ingame it should be placed in that namespace, I think.

**Comment by mexmer** [comment]
@Sibz this doesn't add native ingame programming interface, you will need to change to this type, and is not in ingame namespace as said @lord-devious

also, since you adding summary for filed, interface should have also summary, this summary will be visible in documentation

**Comment by Sibz** [comment]
@mexmer 
> this doesn't add native ingame programming interface, you will need to change to this type
I am not sure what you mean here

**Comment by lord-devious** [comment]
I forgot to say; great idea :smile:

**Comment by Sibz** [comment]
Updated as per last commit. This means line in MySandboxGame.cs wasn't needed, is that what you meant @mexmer ?

**Comment by mexmer** [comment]
yes, it is not needed, if you define it this way.
also it has now propert inheritance and placement in both modapi and ingame script .... at least that's what i observer on other interfaces, that are available in PB

**Comment by Sibz** [comment]
@OndrejPetrzilka Doesn't appear possible now the base definition `MyObjectBuilder_OxygenContainerObject` is in Vrage.Game as it cannot implement interface in sandbox.modapi.ingame namespace.
If it is possible, hints on how would be appreciated.

**Comment by mexmer** [comment]
don't be haste, i will check it later ... there might be a way
oxy bottle is special type of item, since it's kind of container.

**Comment by Sibz** [comment]
@mexmer Thank you!

**Comment by mexmer** [comment]
here you go #299
approach from different side tho', not just because of object builders.

**Pull request closed without merging**
