### PR TITLE
 Add projector only show can build

### PR DESCRIPTION
**Pull request by yajiedesign**
add some checkbox with projector only show can build block.

### CODE REVIEW

**Comment by Roberto5** [comment]
good idea, maibe now the projector will not slow the game?

**Comment by Phoenix84** [comment]
Just to be clear, what does this do?
Does disable the projection itself, but you can still build if you know where the blocks are?

**Comment by JCMais** [comment]
@Phoenix84 from what I can tell, it hides the projection of blocks that were already welded.

**Comment by zrisher** [comment]
Yes this would be significantly more legible if the names were changed to `onlyProjectBuildable` instead of `onlyCanBuildBlock`

**Comment by RossM** [comment]
You need to add your new field to the sync code, otherwise it won't work correctly in multiplayer.

**Comment by yajiedesign** [comment]
@RossM is add in SetNewOffset

**Comment by OndrejPetrzilka** [comment]
Alex will review that before merging, the names should be changed to:
Show only buildable

**Comment by yajiedesign** [comment]
change ok

**Comment by yajiedesign** [comment]
@OndrejPetrzilka  change ok

**Pull request merged**
