### PR TITLE
IMyBatteryBlock: Added IsCharging property

### PR DESCRIPTION
**Pull request by Sibz**
IsCharging returns true if IsWorking and block has been set to recharge.

Compiled And Tested OK.

### CODE REVIEW

**Comment by THDigi** [comment]
You can already get those values, I think it would be more useful to know if it's actually charging, maybe a check in power input :P

**Comment by Sibz** [comment]
How do I retrieve if block is set to recharge currently?

**Comment by THDigi** [comment]
It doesn't have a GetValue() parameter ?
Then it only leaves the `.GetAction().WriteValue()` which is unreliable, so nevermind xD

In that case, add 2 fields, one only returns the charge checkbox's status (without caring for IsWorking) and one that tells you if the battery currently draws power.

**Comment by Sibz** [comment]
Well thinking about it, I may as well just expose ProducerEnabled true if its not charging, aka producing power.
As for power consumption, that's a different matter, other blocks consume power too, so this would be better if IMyPowerConsumer was exposed with required fields.
Closing this pull in favour of ProducerEnabled.

**Pull request closed without merging**
