### PR TITLE
Removing redundancies in code, replace some code with LINQ equivalent…

### PR DESCRIPTION
**Pull request by Aminion**
…, fixing code formatting in VRage.Network

### CODE REVIEW

**Comment by mexmer** [comment]
first, don't touch network code
second, linq is not used due perfomance

**Comment by lord-devious** [comment]
Performance and memory allocations.

**Comment by mexmer** [comment]
too much memory allocations affects performance ;o)

**Comment by RossM** [comment]
Rule 1 of high-performance C# is don't allocate objects inside loops. The object allocation itself is super cheap, but the extra load it puts on the GC will kill you.

**Comment by JCMais** [comment]
I don't know about Keen, but the rule of thumb for the majority of other projects I've seen, is that You should avoid pull requests that change too many code at the same time, stuff like that is very prone to merge conflicts. :p

**Comment by No-Brain** [comment]
Yeah no.

**Pull request closed without merging**
