### PR TITLE
Exposed the DisplayName property in IMyCubeGrid

### PR DESCRIPTION
**Pull request by lord-devious**

### CODE REVIEW

**Comment by lord-devious** [comment]
Actually, thinking about it, just Grid would suffice. I think it's the word "cube" that's bugging me.

**Comment by liorabel** [comment]
Immersion in modding? That's a bit of a stretch... :)

**Comment by lord-devious** [comment]
For ingame scripting.

---- Lior Abel wrote ----

**Comment by Spartan322** [comment]
The issue with the name is it take a lot of workaround to get that to work (cubegrid name is used because of proper naming conventions) but my only issue is the "MY" everywhere which is already a bad naming convention, should either not be there or be something else.

**Comment by aequasi** [comment]
What kind of workaround are you talking about?

**Comment by Spartan322** [comment]
I am referring to his comments about the naming conventions (which might do better in a separate issue if it is talked any longer, I am revering to his immersion breaking in scripts btw)

**Comment by aequasi** [comment]
I know what you are referring you, I was asking what kind of a "workaround" you think would be required.

**Comment by Spartan322** [comment]
(sorry, stated it above)

**Comment by lord-devious** [comment]
Coding standards and structures is my responsibility at work. Having a name other than CubeGrid would not be breaking naming conventions because it would still describe what it is. But as I said, it is a moot point, it is what it is, Keen decides.

**Comment by lord-devious** [comment]
**aargh**, accidentally closed it...

**Comment by aequasi** [comment]
You can re-open @lord-devious? lol

**Comment by lord-devious** [comment]
How? Can't find any way to do it.

**Comment by aequasi** [comment]
Right next to the "Comment" button below the chat thingy

**Comment by lord-devious** [comment]
Nope. I'm guessing they're removed that privilege to keep control.

**Comment by aequasi** [comment]
I just tested it on my own issue: https://github.com/KeenSoftwareHouse/SpaceEngineers/issues/37

**Comment by aequasi** [comment]
Ahhh, yours is a PR. That explains why.

**Pull request closed without merging**
