### PR TITLE
Fix typo in assembler/refinery control panel: Efficinecy -> Efficiency

### PR DESCRIPTION
**Pull request by Maeyanie**
It was bugging me. :)

### CODE REVIEW

**Comment by lord-devious** [comment]
Finally :wink:

**Comment by mexmer** [comment]
most likely they planed to fix this when adding localized strings, instead of hardcoded ones
i suggested you change your code to use localized strings.

**Comment by lord-devious** [comment]
Also; shouldn't make pull request from your master.

**Comment by No-Brain** [comment]
This should be using localized strings.
Any hardcoded texts are either bug or debug.

**Pull request merged**
