### PR TITLE
Single- and Multiline Text Box Fixes

### PR DESCRIPTION
**Pull request by lord-devious**
A bunch of quality of life fixes for the single- and multiline text boxes, mostly intended to improve the programmable block code editing but also improves text panels.

### CODE REVIEW

**Comment by Sibz** [comment]
:+1:   Awesome work!

**Comment by Phoenix84** [comment]
Does this fix the arrow keys jumping multiple character positions on a single press?

**Comment by lord-devious** [comment]
Horizontally yes. You just reminded me that I intended to fix the up/down problem for the multiline text box as well. Back to coding :smile:

**Comment by Phoenix84** [comment]
Excellent!
Do you think you could fix the mouse selection issue while you're at it?
When highlighting text, quite often the last few characters don't get highlighted if the mouse leaves the text box area. This is mostly when selecting from right to left.

**Comment by lord-devious** [comment]
If anyone feels called upon to be an "outside" tester for this, so @OndrejPetrzilka and @No-Brain's job gets easier, it'd be appreciated.

**Comment by THDigi** [comment]
Testing this in the PB's text area.

When holding a typed key down it seems to repeat fine (my keyboard repeat setting is at max) but the arrow movement is slower than that.

And while moving down with the arrow key you can press up to instantly go up, in reverse there's a delay.

**Comment by lord-devious** [comment]
I just used Keen's original setup, although I sped up the repeat for the system keys a bit. I could use the system's repeat key setting but I don't feel it's worth the effort.

I'll check the extra delay.

**Pull request merged**
