### PR TITLE
Add rotation and elevation clamping to the laser antenna.

### PR DESCRIPTION
**Pull request by Phoenix84**
This adds the ability to set rotation and elevation limits to the laser antenna, just like the turrets have.

The code is pretty much copied from the turret itself. I wish the laser antenna and turrets shared common code, but it appears they are each implemented on their own.

### CODE REVIEW

**Comment by Phoenix84** [comment]
Done, and done.
Additionally, the message will be shown and in-game boolean will be set if the hardcoded elevation limit is also reached.
I decided to leave that limit in, as the turret still has it, and I didn't want to risk changing behavior there.

**Comment by mexmer** [comment]
nice

**Comment by Phoenix84** [comment]
Ok, I merged master. I hope I did that right. Never did a git merge before.

**Comment by OndrejPetrzilka** [comment]
Sometimes it's good to manually move your code in resx files few elements above to prevent merging issues :)

**Comment by Phoenix84** [comment]
Good idea, Ondrej. I'll do that next time. :+1:

**Pull request merged**
