### PR TITLE
FIX. Check availability "Convert To Ship" button.

### PR DESCRIPTION
**Pull request by JimLess**
Checks for grid ownership before displaying the 'Convert To Ship' button, similar to the 'Rename' button's behavior.

### CODE REVIEW

**Comment by zrisher** [comment]
"Checks for grid ownership before displaying the 'Convert To Ship' button, similar to the 'Rename' button's behavior."

Pretty sure this is a highly requested feature. I know the majority of people on my server would like to have this additional safety mechanism.

**Comment by JimLess** [comment]
zrisher, thanks.

**Comment by mexmer** [comment]
OnRecreateControl is correct place for this check.

as for redrawing, that could be fixed also. i will check code and let you know. Possibly redraw can and should be triggered when ownership changes. Since usually you don't have lot of ownership changes in small timeframe

**Comment by JimLess** [comment]
is up-to-date.
Please! Add this fix into next update!

**Pull request closed without merging**
