### PR TITLE
Warhead damage

### PR DESCRIPTION
**Pull request by midspace**
For #1

### CODE REVIEW

**Comment by fabricator77** [comment]
Was experimenting with Warheads earlier, having the ability to dial up/down the damage to create different types of explosives is needed.

**Comment by midspace** [comment]
I think I need to add a minimum value check of zero into the MyWarheadDefinition.Init(), to prevent negative numbers.

**Comment by OndrejPetrzilka** [comment]
Please update your branch and add default value into object builder so if there's any modded warheads, it has correct damage.

public float WarheadExplosionDamage = 15000;

**Comment by midspace** [comment]
This says "This pull request contains merge conflicts that must be resolved."
Anyone know how to resolve this, or should I create a new branch?

**Comment by Spartan322** [comment]
@midspace You should probably do a hard reset update to a new branch, and just copy all the relevant code, you'd pretty much do the same thing anyway without a hard reset but it probably have a bunch of junk commits in it.

**Comment by zrisher** [comment]
```
git checkout master
git pull (whatever you named KSH's remote) master
git checkout WarheadDamage
git rebase master
(fix conflicts as you go)
```

**Comment by midspace** [comment]
Replaced by https://github.com/KeenSoftwareHouse/SpaceEngineers/pull/278

**Pull request closed without merging**
