### PR TITLE
[Bugfix] Fixed fields (Vector3D .X, .Y, .Z), which also stops very bad crashes in Win10. Fixed custom Enums.

### PR DESCRIPTION
**Pull request by lord-devious**
Before this fix, the following script crashes - sometimes safely, in Win10 sometimes even so hard there's no crash log.

This is now fixed, the vector X/Y/Z now return expected values - and no crashes.

```C#
void Main(string argument) 
{ 
    var pos = Me.GetPosition();
    Echo(pos.X + " " + pos.Y + " " + pos.Z);

    VRage.MyFixedPoint fp=(VRage.MyFixedPoint)10.12; 
 
  long rv=fp.RawValue; 
  Echo(rv.ToString()); 
 
  Echo(fp.RawValue.ToString()); 
 
//  Echo( ((VRage.MyFixedPoint)10.12).RawValue.ToString() ); 
}
```

Enums are also fixed. You can now do:
```C#
enum A {
    A,
    B,
    C
}

void Main() {
    Echo(A.B.ToString());
}
```

### CODE REVIEW

**Comment by lord-devious** [comment]
Ok... Enums /work/ but their ToString is a bit wonky still. Working on it.

**Comment by lord-devious** [comment]
Done!

**Comment by Trojaner25** [comment]
+1

**Comment by LynnuxX** [comment]
Does it only fix Vector3/3D or also other stuff like MyBlockOrientation ?
Using directions Forward and Up in programmable blocks seems to be bugged (wrong value returned by one of them)

**Comment by lord-devious** [comment]
*Should* fix any and all field access. Vectors were only used as example.

**Comment by LynnuxX** [comment]
Very nice !

**Comment by lord-devious** [comment]
@Fujtajblik or whoever else in charge - a warning: I fixed the conflicts, but I was not able to run the game and test this after the fix. Is there a way I can get the current source to run?

**Comment by lord-devious** [comment]
The important parts of this one was merged an alternate way.

**Pull request closed without merging**
