### PR TITLE
FIX: various UI transparency issues

### PR DESCRIPTION
**Pull request by mexmer**
fixes for diffent parts of terminal UI, that disapear when background transparency is set to 0

http://imgur.com/HJN2AOH
http://imgur.com/a/ITLJY
material icons
http://imgur.com/spWkRkr
borders
http://imgur.com/kxownWa
http://imgur.com/MFmAnOk

### CODE REVIEW

**Comment by FavioGalvis** [comment]
supporting! :+1:

**Comment by mexmer** [comment]
rebased and fixed conflicts

**Comment by mexmer** [comment]
rebased and fixed conflicts and missing code in new ui controls

**Comment by mexmer** [comment]
cleanup - no longer working on this

**Pull request closed without merging**
