### PR TITLE
Clearer BoundingBox '!=' operator.

### PR DESCRIPTION
**Pull request by mafagafogigante**

### CODE REVIEW

**Comment by No-Brain** [comment]
Doesn't do anything. Don't be that guy.

**Comment by OndrejPetrzilka** [comment]
One thing is maintainability other thing is performance.
For performance this is preferred way (for equals):

                return a.Min.X == b.Min.X
                    && a.Min.Y == b.Min.Y
                    && a.Min.Z == b.Min.Z
                    && a.Max.X == b.Max.X
                    && a.Max.Y == b.Max.Y
                    && a.Max.Z == b.Max.Z;

**Comment by mafagafogigante** [comment]
@OndrejPetrzilka so... I don't get it. Just write this in the equals code and reverse it for the not equals operator. I think the MS compiler is good enough to inline equals code in the other function.

**Comment by zrisher** [comment]
It does seem a bit more DRY to include that logic as the equality method for BoundingBox.

**Pull request closed without merging**
