### PR TITLE
Complete Russian translation

### PR DESCRIPTION
**Pull request by KionX**

### CODE REVIEW

**Comment by sjsoft2015** [comment]
In Russian this is wrong: "Мало энергии скафандра."

**Comment by mexmer** [comment]
this doesn't belong to source code.
for translations there is subforum on forums also this
https://www.getlocalization.com/SpaceEngineers/

**Comment by KionX** [comment]
every word 10 times translated. and does not determine the translation.
let it be here. maybe someone should.

**Comment by lord-devious** [comment]
These files will be overwritten by their translation tool the second they regenerate the translations.

**Pull request closed without merging**
