### PR TITLE
LMB/RMB will act like T/K buttons if there is nothing selected in the current toolbar.

### PR DESCRIPTION
**Pull request by kehitt**
A simple feature suggested on [/r/spaceengineers](https://www.reddit.com/r/spaceengineers/comments/3dbe72/request_leftright_click_should_be_tk_when_nothing/) and got heavily upvoted.

### CODE REVIEW

**Comment by krypt-lynx** [comment]
+1
For total happiness need doors must do open/close by mouse click on door body.

**Comment by mexmer** [comment]
how does it behave, if you have tool in hand?

**Comment by kehitt** [comment]
@mexmer It will only behave like that if you have nothing in your hands.

**Comment by FavioGalvis** [comment]
:+1: Quality of Life

**Comment by lord-devious** [comment]
@krypt-lynx that is a whole 'nother bag of bones.

I think I'm gonna enjoy this one, @kehitt. Good work! Sometimes the best additions require the least amount of changes.

:+1:

**Comment by kehitt** [comment]
I just realized that there is an issue with this code. If you select an item and switch a page, you will be able to use/access terminal with this item in your hand. I'm trying to figure out a simple solution, but have no luck far.

**Comment by mexmer** [comment]
that's why i asked about tools. if you switch to empty toolbar, your check will fail. since there will be nothing selected (empty toolbar), yet lmb is primary fire ...

**Comment by kehitt** [comment]
Yeah, there seems to be no simple way of fixing this. Closing this PR for now.

**Comment by lord-devious** [comment]
Pity.

**Pull request closed without merging**
