### PR TITLE
Turret ammo fix for DS/MP

### PR DESCRIPTION
**Pull request by joemorin73**
Similar to issue https://github.com/KeenSoftwareHouse/SpaceEngineers/issues/213

This corrects the ammo consumption in multiplayer environment by adding IsServer check.

### CODE REVIEW

**Comment by zrisher** [comment]
Big issue in Multiplayer. I would really like to see this incorporated.

**Comment by joemorin73** [comment]
@mexmer, oops.  You're right.

**Comment by joemorin73** [comment]
Removed the extra brackets.

**Comment by Mrjinx453** [comment]
+1 Would love to see this fixed

**Comment by mexmer** [comment]
i would like to see numbers, also impact on game response.
consider people using weapon groups, firing like 20 gatlings at once.

while i understand nature of the fix, i'm not sure, if this will not create some adverse effects (lagspikes because of tons of sync packets).

**Comment by joemorin73** [comment]
I'm not sure there is traffic being generated from this scenario.  I'm adding a check for the game to validate the server is removing ammo.  If anything, it should be reducing traffic as all other machines won't be removing ammo and sending out messages about ammo removal to the other machines.

**Comment by mexmer** [comment]
that's a good point, i didn't thought about that.

**Comment by joemorin73** [comment]
It's an interesting thing to think about.  Is it possible there are other points in the code that are generating unnecessary traffic?

**Comment by joemorin73** [comment]
Closing in favour of other PR

**Pull request closed without merging**
