### PR TITLE
Add MemoryLimits checkbox to OptionsGame

### PR DESCRIPTION
**Pull request by KionX**
most people don't even know about this option
now it is well illustrated and easy to switch

### CODE REVIEW

**Comment by lord-devious** [comment]
Something is weird with your PRs. How come all these old commits show up?

**Comment by mexmer** [comment]
because of wrong branching

**Comment by lord-devious** [comment]
Definitely seems like it.

**Comment by No-Brain** [comment]
This should not be a user facing option as it can cause crashes when disabled.
It is already possible to disable this from config.

**Comment by KionX** [comment]
most people don't even know about this option
now it is well illustrated and easy to switch

**Comment by MeusRex** [comment]
And even less people will know what the consequences are... Which will propably result in a wave of "bug" reports.

**Comment by No-Brain** [comment]
This only creates problems and solves nothing.

**Comment by KionX** [comment]
I enjoyed it a lot. noticed nothing wrong. much worse when you suddenly can't put a block

**Comment by No-Brain** [comment]
This only happens on 32bit systems. Windows supports 64bit since 2001. You should really consider upgrading.

**Comment by KionX** [comment]
but this is 32 bit version

**Comment by Spartan322** [comment]
This doesn't appear to add anything, seems only to be made to crash

**Pull request closed without merging**
