### PR TITLE
Fix against vibrating and shaking small 1x1 suspension block

### PR DESCRIPTION
**Pull request by thelastWallE**
Fixes the vibrating of the small 1x1 suspension if value has been changed too quickly from min to max.
See comments on Pull Request https://github.com/KeenSoftwareHouse/SpaceEngineers/pull/120

### CODE REVIEW

**Comment by thelastWallE** [comment]
Tested it, but who knows. Maybe someone other can test this again to be sure.

**Comment by THDigi** [comment]
The vibration happens for largeship too btw xD

**Comment by THDigi** [comment]
Actually, in my fix+improvements PR I'll make SuspensionLimit obsolete, MinHeight and MaxHeight will also control the physical limit that the suspension can go to, so this won't be necessary anymore, sorry :P

**Comment by thelastWallE** [comment]
Ok was reading your branch for this.
Closing this.
Then i asume that your new PR is finished for next weeks patchday? ;)

**Comment by THDigi** [comment]
I've finished it (https://github.com/KeenSoftwareHouse/SpaceEngineers/pull/193), hopefully it will be pulled in time to be included in next week's patchmas :}

**Pull request closed without merging**
