### PR TITLE
Gui transparency

### PR DESCRIPTION
**Pull request by mexmer**
transparency setting for ingame GUI.
transparency settings affects only terminal screen, toolbar config screen, and game settings screen (this one, to show preview what it will look like)
terminal foreground transparency can be set from 10 to 100%
terminal background transparency can be set from 0 to 100%
http://imgur.com/a/i8vpz

### CODE REVIEW

**Comment by thelastWallE** [comment]
Must..have..this!

**Comment by mexmer** [comment]
rebased onto current master

**Comment by Geneticus** [comment]
+1,000,000 :)

**Comment by THDigi** [comment]
Awesome !

**Comment by zrisher** [comment]
Yes please.

**Pull request merged**
