### PR TITLE
Adding adjustable Flamecolor

### PR DESCRIPTION
**Pull request by DevilDesire**
Adding Slider to adjust the  Thrusterflame color in Terminal

### CODE REVIEW

**Comment by lord-devious** [comment]
Isn't this a duplicate of #323 ?

**Comment by DevilDesire** [comment]
i dont saw this before, ist maybe a duplicate. But selfcoded before i see #323 

InGame Screenshot (if anyone would to see):
http://i.imgur.com/Sdqlzsm.jpg

**Comment by lord-devious** [comment]
Point is there's some good arguments in there as to why this shouldn't be available just like that.

**Comment by lord-devious** [comment]
Also it's important to try to look through what is already done so Keen don't get unnecessarily many PRs to review, there's already quite many :smile:

**Comment by BlackRedDead** [comment]
ehm, - how can i vote for this?

**Comment by lord-devious** [comment]
@BlackRedDead there is no voting system. Also you should check out #323 as this one is a duplicate. There's some discussion that went on over there that is relevant.

**Comment by BlackRedDead** [comment]
i checked the code - its not duplicate! :P
but no idea how to use that code now... :-/
want it ingame - how to tell that the devs?! (what is the reason of having public code without a voting system for changes?!)

**Comment by BlackRedDead** [comment]
@lord-devious :
hmm... maybe i have to take more time on github to understand some things :-)
but could you give me some helpfull hints where to look for actual using this code? (knowledge&usage)

**Comment by lord-devious** [comment]
@BlackRedDead To be honest, I'm not sure I would bother if I were you. The game version you would get using this code is a month old. That's 4 updates ago. And the way to be able to use this is to compile it yourself with Visual Studio and run a local version. Also you won't get the 64-bit version, so it's rather restricted memory wise. It's quite involved just to be able to change colors on your thrusters, wouldn't you say :smile:

**Comment by LeonidasCZ** [comment]
duplicate of #323 closing

**Pull request closed without merging**
