### PR TITLE
BugFix for MyPlugin

### PR DESCRIPTION
**Pull request by sjsoft2015**
1) Keeping all switches that run the process, when it is restarted.
2) Removed pieces block raises an exception when loading with switch
-plugin

### CODE REVIEW

**Comment by OndrejPetrzilka** [comment]
Why not to write into MyLog at all?

**Comment by sjsoft2015** [comment]
Because application crash on start. If u run dedication server with -plugin option u will see this. 
I think logging is required, but there are two process starts, it loads plug twice. The idea should be tweaked to run did not exist, but it can affect large numbers of files.

**Comment by OndrejPetrzilka** [comment]
ok, agree

**Comment by sjsoft2015** [comment]
Created a new pull request #234

**Pull request closed without merging**
