### PR TITLE
Server Join from API

### PR DESCRIPTION
**Pull request by Tyrsis**
This allows scripts to have a player join another multiplayer server.  Same mechanism as if they did a +connect.

### CODE REVIEW

**Comment by joemorin73** [comment]
What?  wait?  is this in reference to the "teleport" discussion on the forums?

**Comment by Tyrsis** [comment]
Not sure what discussion you speak of, but this is a feature I've wanted for awhile.  It will allow a script controlled by the server to send a user to another server for load balance / wormhole style travel between multiple servers.

**Comment by joemorin73** [comment]
Check here:
http://forums.keenswh.com/threads/teleportation-between-servers.7362708/

**Comment by Tyrsis** [comment]
Yes it can be used for that.  But before this source mod there was no way to trigger a server join of another server via api.  This PR changes that.  The other stuff discussed in that thread are different issues completely, all this does make a user join a server.  What you do with that is up to the implementer.  I have 2 servers (Transcend) and I will use it to allow users to travel between the two servers (both servers have synchronized player lists, faction lists and mod lists, so it would be safe to do so).

**Comment by joemorin73** [comment]
I had a similar idea.  The PR is definitely required, but there is a lot more work required.  I'm assuming you will be making an SESE plugin to manage transferring entities?

**Comment by Tyrsis** [comment]
There is a lot more work required, but all that can be done on the server.  This part is a client requirement that had to be met before anything else can be done.

**Comment by Qithe** [comment]
Whoa Whoa Whoa, hold my hoses. Are you seriusly working on a mod/script that would alow jumping betwen servers? 

(Yes, I'm the same guy from the forum. Im the OP)

**Comment by devu** [comment]
Cross server join is indeed very needed in admin community. Thank you for
picking this up Tyrsis!.
But the ultimate goal would be cross server jump. Are you thinking about
this as well?

**Comment by zrisher** [comment]
> (both servers have synchronized player lists, faction lists and mod lists, so it would be safe to do so).

Yes, this part would be great to have in Core too so that everyone can accomplish this "server jump"

**Comment by Tyrsis** [comment]
I renamed it, as it seems to be a little bit misleading.  This is just a server join from API.  This doesn't include synchronization that would allow movement of objects from one server to another.  This just moves clients.

**Comment by devu** [comment]
It wasn't misleading, totally got the idea and functionality behind. Just
saying is just a step closer to object movement across servers that would
be a ultimate goal.
But you kind of answered my question. However with player ID in sync across
different instances it would be much easier to create such mechanism anyway.

If you are focused on client join only, would be possible to join with a
custom flag? To be able to recognize if someone just joined instance
directly or joined from API?

**Comment by IhanaMies** [comment]
With this commit is it possible to connect servers via GPS locations since jump drives were added?

**Comment by joemorin73** [comment]
This commit adds the ability for to change servers via mods. It still requires mods to be made to use it.

**Comment by JimLess** [comment]
now i can use it in my mod =)

**Comment by joemorin73** [comment]
If the community merges are added in today's update.  If not, one week.

**Pull request merged**
