### PR TITLE
Send Message to PB via Laser Antenna

### PR DESCRIPTION
**Pull request by MeusRex**
This addition enables users to set the argument of a programmable block which is connected to the current grid by a pair of Laser Antenna.

It also adds a method to run the script of said pb.

### CODE REVIEW

**Comment by lord-devious** [comment]
Good idea! :smile:

However the TerminalRunArgument property should not be used in this way, since it's purpose is to be used via the Run button in the control panel _only_. It would be better to run the PB with a proper argument, like buttons etc. do.

**Comment by MeusRex** [comment]
So, you say I should just skip setting the TerminalRunArgument field and just run the pb's script with the (string)message as argument?
I guess I can do that, no problem. Thanks btw. for the whole TerminalRunArgument.

**Comment by lord-devious** [comment]
Yes, that's what I'm suggesting. It would probably be more efficient too, a single message rather than two.

**Comment by MeusRex** [comment]
Removed SendRunCommand, since it became redundant.

SendMessage now runs the script of the specified pb with a custom argument, which doesn't replace the argument text field.

**Comment by MeusRex** [comment]
Continued here: https://github.com/KeenSoftwareHouse/SpaceEngineers/pull/75

Now from branch instead of master. (never used git before...)

**Pull request closed without merging**
