### PR TITLE
IMyAssembler: Added queue management functions

### LINKED ISSUE #96: Assembler queue access with ingame script
One of this ingame PB pb is missing is access to assembler queue.

It seems not hard to make current queue visible, but i'm not sure if it will be safe (well i'm pretty sure, it will not), therefore queue will need to be accessed either by functions (addtoqueue, removefrom queue), or using interface (IMyQueue), like is for IMyInvetory.

I'm more inclined to IMyQueue (or whatever we will call it) as safe access to queue

ideas welcome

### PR DESCRIPTION
**Pull request by Sibz**
Added the following functions:
```c# 
bool AddQueueItem(string itemType, string subtypeName, int amount);
int GetQueueCount();
IMyAssemblerQueueItem GetQueueItemAt(int idx);
void RemoveQueueItemAt(int idx);
void ClearQueue();
int CountQueueItems(string itemType, string subtypeName);
```
Added interface IMyAssemblerQueueItem

Added class MyAssemblerQueueItem to MyAssembler

Uses existing functions that are sync friendly for modifying the queue.

Compiles and tested OK.
In game test code: http://pastebin.com/ybWuqxTw

Closes #96

### CODE REVIEW

**Comment by Souper07** [comment]
Long overdue. Nice work!

**Comment by joemorin73** [comment]
What would you think about adding an overload for AddQueueItem?

bool AddQueueItem(string itemType, string subtypeName, int amount, int idx);

Allow insertion within the queue.

**Comment by Sibz** [comment]
@joemorin73 Yes I was thinking about that, it would be easy to do. I'll add that in tonight when I get home.

**Comment by Sibz** [comment]
@joemorin73 Added as a optional parameter, default is -1 (add to end of queue).

**Comment by joemorin73** [comment]
Excellent.  This should bring in some impressive ingame production scripts.

How I suck.  Any thoughts on Disassembly or how the code works when it's in Disassembly mode?

**Comment by mexmer** [comment]
@joemorin73 there is not much diffence between assemble mode and dissassemble mode.

in dissasemble mode it "produces" ingots from components/tools, that's about it.

**Comment by joemorin73** [comment]
True.  But there is nothing in the interface to check which mode the assembler is in and change the mode.

**Comment by mexmer** [comment]
@joemorin73 but there is
https://github.com/KeenSoftwareHouse/SpaceEngineers/pull/207
this allows you to read state of any On/Off or checkbox control as bool or using SetValue to change it.

**Comment by joemorin73** [comment]
Ahhh!  Then if AddQueue can also add to the disassembly queue, we are set!

**Comment by Aleks976** [comment]
Is there any word on whether these changes will be merged with master or not?

**Comment by Sibz** [comment]
I am still hoping, theres not been much merge activity lately, I assume it because they are working hard to introduce planets and/or netcode.

**Comment by paradineai** [comment]
I am not sure if this question is in the correct location but: would it be possible to get the ability to add/remove items to/from the production queue in the assembler added to the api so we can use an in game script to control the production of items directly just like we are able to change the image or text on an lcd panel? This would allow the people who are righting the scripts to make a quota management script to make the assemblers keep a certain amount of items available in their cargo containers inventory. For example if I made a script to allow me to keep a minimum of 10k steel plates in my inventory it would be able to check all of the cargo containers on my ship/station and count the number of steel plates. Then if I have >= 10k steel plates total it does nothing but once I remove enough to get below 10k steel plates it tells my assembler to make the number needed to bring it back up to a total of 10k. If this question is in the wrong location then I ask that KSH move it to the correct one and let me know of the error. Also I ask these questions because I am not very good at programing myself and would rather leave it to someone whom knows more than I do.

**Comment by zrisher** [comment]
@paradineai:

**In general**, report issues (either Bugs or Feature Requests) in the [Issues section](https://github.com/KeenSoftwareHouse/SpaceEngineers/issues). Discuss implementations of bug fixes and features in their respective PRs, like this page. In this case, Sibz mentioned the issue this is meant to fix in his initial comment - #96. I would look there to see if the issue he's attempting to fix is the same you have. If it's similar enough but you had additional requests you can add them there, otherwise you can open a new one.

**In this case**, it looks to me like what you're asking for is exactly what he's implemented.

**Comment by Sibz** [comment]
Conflicts, will re-do request.

**Pull request closed without merging**
