### PR TITLE
Mass property for IMyCubeBlock and IMySlimBlock

### PR DESCRIPTION
**Pull request by mexmer**
Property to retrieve block mass in modapi and ingame scripts
This property retrieves block mass from block definition (eg. not virtual mass, like spaceball hass, but blueprint one)

### CODE REVIEW

**Comment by LeonidasCZ** [comment]
MyCubeBlock also has GetMass function, no need to add Mass property and call SB.GetMass() (which then calls FatBlock.GetMass())

**Comment by mexmer** [comment]
GetMass() function is not defined in IMyCubeBlock interface. Therefore you cannot use it in ingame program scripts.

Also Property accessors looks better than functions ....

**Comment by LeonidasCZ** [comment]
Yes property on the interface side is allright. 
Just the MyCubeBlock.Mass property is redundant.
You can implement IMyCubeBlock.Mass same as
       float IMySlimBlock.Mass
       {
             get { return GetMass();  }
       }
You can use any member/method when implementing the ModAPI interface so 
       float IMyCubeBlock.Mass
       {
           get { return GetMass(); }
       }
in MyCubeBlock_ModAPI.cs would be correct.

**Comment by mexmer** [comment]
not sure, if it's this one - if you mean
MyCubeBlock.cs line 118
        public float Mass { get { return SlimBlock.GetMass(); } }

i've done it, to mimic Min/Max definition. might remove it, of course.

**Comment by LeonidasCZ** [comment]
Yes, that one.
I see that makes sense, but its slightly different case. Min/Max are just shortcuts but in case of the mass cubeblock can get it from itself, SlimBlock.GetMass() would do it anyway. Also generally beware of duplication, having both MyCubeBlock.Mass and MyCubeBlock.GetMass() is confusing. :)

**Comment by mexmer** [comment]
done

**Comment by OndrejPetrzilka** [comment]
Thanks, I like how simple it is

**Pull request merged**
