### PR TITLE
Update README.md section 'To get started using GitHub'

### PR DESCRIPTION
**Pull request by KionX**

### CODE REVIEW

**Comment by zrisher** [comment]
Yes, you don't have to write out the remote location every time! View all your remotes with `remote -v`. Manage them with:

```
remote add name location   - to add a remote named "name" at "location"
remote set-url name location  - to change the location of "name" to "location"
remote remove name  - to remove the remote "name"
```
i.e.
```
remote add ksh https://github.com/KeenSoftwareHouse/SpaceEngineers
remote set-url ksh git@github.com:KeenSoftwareHouse/SpaceEngineers
remote remove ksh
```

**Comment by mexmer** [comment]
@zrisher that's not what i meant.

when you fork other person repo on Github, and then clone it to your computer, and list remotes using 'git remote -v', you will see, there is remote with name "otherperson" pointing to git url of repository you forked. 

Github already does this for you, when you fork.
Therefore using remote github already created for you is more "natural" than manually entering url.

**Comment by JJRcop** [comment]
This is [kiiinda my fault](https://github.com/KeenSoftwareHouse/SpaceEngineers/pull/115#issuecomment-104035344). I just intended it for @KionX, not really for the readme, haha. Oh well.

**Comment by THDigi** [comment]
I don't think 'git reset --hard' and 'git push --force' should be recommended in the readme since those aren't safe, expecially if you don't understand what they do, people will just lose their work.

**Comment by OndrejPetrzilka** [comment]
Create another section in **How to contribute** and merged your changes manually

**Pull request closed without merging**
