### PR TITLE
FIX: IMyTextPanel.WritePrivateText

### PR DESCRIPTION
**Pull request by mexmer**
- due typo in code, variable was reset prior sending sync message, and text was reset, when using pb.

### CODE REVIEW

**Comment by THDigi** [comment]
Hmm, PrivateTitle is also in need of this fix then.

**Comment by mexmer** [comment]
@THDigi i see, you are right. will fix that later.
i don't use private text at all, just checked for this, because of report on forums.

**Comment by mexmer** [comment]
rebased and added fix for title

**Comment by mexmer** [comment]
could we get this merged soon, so we can finally use privatetext/privatetitle and not only publictext/publictitle?

**Comment by LeonidasCZ** [comment]
merged with #394 thanks

**Comment by mexmer** [comment]
yes, thanks

**Pull request closed without merging**
